# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Jenkins")
  end

  lane :fabric do

  increment_build_number
  # build your iOS app
  build_app(
    scheme: "Jenkins",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    # keys for organization: MD's project
    api_token: "b9a7e6ca6f9fe89bfbe301522d71cad50a61363a",
    build_secret: "389781f4a4ea1c2f4a119fbd82c823e1cb28dd5cb8bc00b7a708ed15d61850b1",
    groups: "Beta"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
  end
end
